version: "3.5"
services:
  database:
    env_file: .env
    build:
      context: ./Database/
      dockerfile: Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
