version: "3.5"
services:
  database:
    env_file: .env
    build:
      context: ./Database/
      dockerfile: Dockerfile
    ports:
      - "3306:3036"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
